function errors = computeParametrizationErrors(IMInfo, yData)
% Compute the normed mean distance of trajectories in yData and the same
% trajectories projected onto the manifold defined by IMInfo
%
% INPUT
% IMInfo        struct generated by IMGeometry
% yData         (n x 2) cell array containing trajectories

etaData = projectTrajectories(IMInfo, yData);
yRec = liftTrajectories(IMInfo, etaData);
errors = computeTrajectoryErrors(yRec, yData);